### PR TITLE
Created 3 new logo variants

### PR DESCRIPTION
**Pull request by davidbru**
I created 3 new logo variants under the theme "shy":

awesomescreenshot-2017-10-13t20-46-10-971z

awesomescreenshot-2017-10-13t20-46-36-061z

awesomescreenshot-2017-10-13t20-50-54-905z

### CODE REVIEW

**Comment by bryanbraun** [comment]
YESSSSSSSSSSSSSS!!!!!!

image

@davidbru, these are fantastic! I especially love the first one 😍 .

I'm merging these right away. I can't wait to get these all hooked up and working. 🎉

**Comment by davidbru** [comment]
nice to hear :)

**Comment by bryanbraun** [comment]
Hey @davidbru, I just wanted to let you know that I've updated my site to randomly pull in one of the logo variations (including yours) on each page refresh. [More details here](https://www.bryanbraun.com/2017/11/19/hacktoberfest-2017/#hack-my-logo).

Thanks again!

**Comment by davidbru** [comment]
Thanks for the heads up. Glad you merged them :)

**Pull request merged**
